name: Xiaomi MIUI/HyperOS Port Build

on:
  workflow_dispatch:
    inputs:
      input_base_url:
        description: 'Base ROM URL to build'
        required: true
      input_port_url:
        description: 'Port ROM URL to build'
        required: true

jobs:
  Build_Status:
    runs-on: ubuntu-latest
    steps:
      - name: Clean All Junk,App
        run: |
          docker rmi `docker images -q` || true
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d || true
          sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell mysql* php* || true
          sudo apt -y autoremove --purge || true
          sudo apt -y autoclean || true
          sudo apt clean || true

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 1024
          root-reserve-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Checkout code
        uses: actions/checkout@main

      - name: Checkout WORKSPACE
        run: |
          git clone -b old https://${{ secrets.PRIVATEP_TOKEN }}@github.com/ndtai1527/XimiHarem.git

      - name: Set up Time
        run: |
          echo "Setting Vietnam timezone"
          sudo timedatectl set-timezone Asia/Ho_Chi_Minh

      - name: Install Stuff
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 rclone python-is-python3 wget python3 lz4 python3-pip dialog aapt busybox zip erofs-utils unzip p7zip-full zipalign zstd bc openssl python-protobuf python xmlstarlet
          sudo pip3 install ConfigObj
          sudo pip3 install telebot
          sudo pip3 install setuptools

      - name: Install OpenJDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Giving Permission
        run: |
          cd XimiHarem
          sudo chmod 777 -R *

      - name: Working...
        env:
          BASE_URL: ${{ inputs.input_base_url }}
          PORT_URL: ${{ inputs.input_port_url }}
        run: |
          cd XimiHarem
          sudo bash build.sh "$BASE_URL" "$PORT_URL"
